package com.hackathon.codegen.generator;

import com.hackathon.codegen.model.GeneratedArtifacts;
import com.hackathon.codegen.model.ResourceRecommendation;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@Slf4j
@Service
public class FileGeneratorService {

    /**
     * Generate all configuration files based on recommendations
     */
    public GeneratedArtifacts generateArtifacts(ResourceRecommendation recommendation) {
        log.info("Generating artifacts for service: {}", recommendation.getServiceName());

        List<GeneratedArtifacts.GeneratedFile> files = new ArrayList<>();

        // 1. Generate Kubernetes deployment.yaml
        files.add(generateKubernetesDeployment(recommendation));

        // 2. Generate application.properties
        files.add(generateApplicationProperties(recommendation));

        // 3. Generate Helm values.yaml
        files.add(generateHelmValues(recommendation));

        // 4. Generate README.md
        files.add(generateReadme(recommendation));

        // 5. Generate azure-pipelines.yml (optional)
        files.add(generateAzurePipeline(recommendation));

        log.info("Generated {} files for {}", files.size(), recommendation.getServiceName());

        return GeneratedArtifacts.builder()
                .serviceName(recommendation.getServiceName())
                .files(files)
                .success(true)
                .build();
    }

    /**
     * Generate Kubernetes deployment.yaml
     */
    private GeneratedArtifacts.GeneratedFile generateKubernetesDeployment(ResourceRecommendation rec) {
        String serviceName = rec.getServiceName();
        String cpuRequest = rec.getKubernetes().getCpuRequest();
        String cpuLimit = rec.getKubernetes().getCpuLimit();
        String memoryRequest = rec.getKubernetes().getMemoryRequest();
        String memoryLimit = rec.getKubernetes().getMemoryLimit();
        String xms = rec.getJvm() != null ? rec.getJvm().getXms() : "256m";
        String xmx = rec.getJvm() != null ? rec.getJvm().getXmx() : "512m";

        String content = String.format("""
apiVersion: apps/v1
kind: Deployment
metadata:
  name: %s
  labels:
    app: %s
    optimized-by: saveyourmoney
    optimization-date: "%s"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: %s
  template:
    metadata:
      labels:
        app: %s
    spec:
      containers:
      - name: %s
        image: %s:latest
        ports:
        - containerPort: 8080

        # OPTIMIZED RESOURCES - Generated by SaveYourMoney AI
        resources:
          requests:
            cpu: "%s"              # ✅ AI Recommended (was suboptimal)
            memory: "%s"           # ✅ AI Recommended (was suboptimal)
          limits:
            cpu: "%s"              # ✅ AI Recommended (was suboptimal)
            memory: "%s"           # ✅ AI Recommended (was suboptimal)

        # OPTIMIZED JVM CONFIGURATION
        env:
        - name: JAVA_OPTS
          value: "-Xms%s -Xmx%s -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError"

        # Health checks
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: %s
spec:
  selector:
    app: %s
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
""",
                serviceName, serviceName,
                LocalDateTime.now().format(DateTimeFormatter.ISO_DATE_TIME),
                serviceName, serviceName, serviceName, serviceName,
                cpuRequest, memoryRequest, cpuLimit, memoryLimit,
                xms, xmx,
                serviceName, serviceName
        );

        return GeneratedArtifacts.GeneratedFile.builder()
                .fileName("deployment.yaml")
                .filePath("k8s/deployment.yaml")
                .content(content)
                .fileType(GeneratedArtifacts.FileType.KUBERNETES_DEPLOYMENT)
                .build();
    }

    /**
     * Generate Spring Boot application.properties
     */
    private GeneratedArtifacts.GeneratedFile generateApplicationProperties(ResourceRecommendation rec) {
        StringBuilder content = new StringBuilder();

        content.append("# SaveYourMoney AI-Optimized Configuration\n");
        content.append("# Generated: ").append(LocalDateTime.now()).append("\n");
        content.append("# Service: ").append(rec.getServiceName()).append("\n");
        content.append("# Confidence Score: ").append(String.format("%.0f%%", rec.getConfidenceScore() * 100)).append("\n\n");

        content.append("# Application\n");
        content.append("spring.application.name=").append(rec.getServiceName()).append("\n\n");

        // Thread pool configuration
        if (rec.getThreadPool() != null) {
            content.append("# OPTIMIZED Thread Pool Configuration\n");
            content.append("server.tomcat.threads.max=").append(rec.getThreadPool().getMaxThreads()).append("\n");
            content.append("server.tomcat.threads.min-spare=").append(rec.getThreadPool().getMinSpareThreads()).append("\n\n");
        }

        // Connection pool configuration (for DB services)
        if (rec.getConnectionPool() != null) {
            content.append("# OPTIMIZED HikariCP Connection Pool\n");
            content.append("spring.datasource.hikari.maximum-pool-size=").append(rec.getConnectionPool().getMaximumPoolSize()).append("\n");
            content.append("spring.datasource.hikari.minimum-idle=").append(rec.getConnectionPool().getMinimumIdle()).append("\n");
            content.append("spring.datasource.hikari.connection-timeout=").append(rec.getConnectionPool().getConnectionTimeout()).append("\n");
            content.append("spring.datasource.hikari.idle-timeout=").append(rec.getConnectionPool().getIdleTimeout()).append("\n\n");
        }

        // Actuator
        content.append("# Actuator\n");
        content.append("management.endpoints.web.exposure.include=health,info,metrics,prometheus\n");
        content.append("management.endpoint.health.show-details=always\n\n");

        // Logging
        content.append("# Logging\n");
        content.append("logging.level.root=INFO\n");
        content.append("logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n\n");

        return GeneratedArtifacts.GeneratedFile.builder()
                .fileName("application.properties")
                .filePath("src/main/resources/application.properties")
                .content(content.toString())
                .fileType(GeneratedArtifacts.FileType.SPRING_PROPERTIES)
                .build();
    }

    /**
     * Generate Helm values.yaml
     */
    private GeneratedArtifacts.GeneratedFile generateHelmValues(ResourceRecommendation rec) {
        String content = String.format("""
# SaveYourMoney AI-Optimized Helm Values
# Generated: %s
# Service: %s
# Confidence Score: %.0f%%

replicaCount: 1

image:
  repository: %s
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

# OPTIMIZED RESOURCES - AI Recommended
resources:
  requests:
    cpu: %s
    memory: %s
  limits:
    cpu: %s
    memory: %s

# OPTIMIZED JVM Configuration
jvm:
  xms: %s
  xmx: %s
  gcType: G1GC
  additionalOpts: "-XX:MaxGCPauseMillis=200 -XX:+HeapDumpOnOutOfMemoryError"

# Health checks
livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8080
  initialDelaySeconds: 20
  periodSeconds: 5

# Auto-scaling (optional)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
""",
                LocalDateTime.now().format(DateTimeFormatter.ISO_DATE_TIME),
                rec.getServiceName(),
                rec.getConfidenceScore() * 100,
                rec.getServiceName(),
                rec.getKubernetes().getCpuRequest(),
                rec.getKubernetes().getMemoryRequest(),
                rec.getKubernetes().getCpuLimit(),
                rec.getKubernetes().getMemoryLimit(),
                rec.getJvm() != null ? rec.getJvm().getXms() : "256m",
                rec.getJvm() != null ? rec.getJvm().getXmx() : "512m"
        );

        return GeneratedArtifacts.GeneratedFile.builder()
                .fileName("values.yaml")
                .filePath("helm/values.yaml")
                .content(content)
                .fileType(GeneratedArtifacts.FileType.HELM_VALUES)
                .build();
    }

    /**
     * Generate README.md with change explanation
     */
    private GeneratedArtifacts.GeneratedFile generateReadme(ResourceRecommendation rec) {
        StringBuilder content = new StringBuilder();

        content.append("# Resource Optimization - ").append(rec.getServiceName()).append("\n\n");
        content.append("**Generated by SaveYourMoney AI** 🤖💰\n\n");
        content.append("**Date:** ").append(LocalDateTime.now().format(DateTimeFormatter.ISO_DATE_TIME)).append("\n\n");
        content.append("**Confidence Score:** ").append(String.format("%.0f%%", rec.getConfidenceScore() * 100)).append("\n\n");

        content.append("---\n\n");

        content.append("## 🎯 Summary\n\n");
        content.append(rec.getRationale()).append("\n\n");

        // Detected issues
        if (rec.getDetectedIssues() != null && !rec.getDetectedIssues().isEmpty()) {
            content.append("## ⚠️ Detected Issues\n\n");
            rec.getDetectedIssues().forEach((issue, description) -> {
                content.append("- **").append(issue).append("**: ").append(description).append("\n");
            });
            content.append("\n");
        }

        // Resource changes
        content.append("## 📊 Resource Changes\n\n");
        content.append("### Kubernetes Resources\n\n");
        content.append("| Resource | Before | After | Change |\n");
        content.append("|----------|---------|-------|--------|\n");
        content.append(String.format("| CPU Request | `100m` | `%s` | ✅ Optimized |\n", rec.getKubernetes().getCpuRequest()));
        content.append(String.format("| CPU Limit | `200m` | `%s` | ✅ Optimized |\n", rec.getKubernetes().getCpuLimit()));
        content.append(String.format("| Memory Request | `256Mi` | `%s` | ✅ Optimized |\n", rec.getKubernetes().getMemoryRequest()));
        content.append(String.format("| Memory Limit | `512Mi` | `%s` | ✅ Optimized |\n\n", rec.getKubernetes().getMemoryLimit()));

        // JVM changes
        if (rec.getJvm() != null) {
            content.append("### JVM Configuration\n\n");
            content.append("| Parameter | Before | After |\n");
            content.append("|-----------|---------|-------|\n");
            content.append(String.format("| `-Xms` | `256m` | `%s` |\n", rec.getJvm().getXms()));
            content.append(String.format("| `-Xmx` | `256m` | `%s` |\n", rec.getJvm().getXmx()));
            content.append("| GC | `default` | `G1GC` |\n\n");
        }

        // Connection pool changes
        if (rec.getConnectionPool() != null) {
            content.append("### Connection Pool (HikariCP)\n\n");
            content.append("| Parameter | Before | After |\n");
            content.append("|-----------|---------|-------|\n");
            content.append(String.format("| Max Pool Size | `5` | `%s` |\n", rec.getConnectionPool().getMaximumPoolSize()));
            content.append(String.format("| Min Idle | `2` | `%s` |\n\n", rec.getConnectionPool().getMinimumIdle()));
        }

        // Cost analysis
        if (rec.getCostAnalysis() != null) {
            content.append("## 💰 Cost Analysis\n\n");
            content.append(String.format("- **Current Monthly Cost**: $%.2f\n", rec.getCostAnalysis().getCurrentMonthlyCost()));
            content.append(String.format("- **Recommended Monthly Cost**: $%.2f\n", rec.getCostAnalysis().getRecommendedMonthlyCost()));
            content.append(String.format("- **Monthly Savings**: $%.2f (%d%%)\n",
                rec.getCostAnalysis().getMonthlySavings(),
                rec.getCostAnalysis().getSavingsPercentage()));
            content.append(String.format("- **Annual Savings**: $%.2f\n\n", rec.getCostAnalysis().getAnnualSavings()));
        }

        // Expected impact
        content.append("## 🚀 Expected Impact\n\n");
        if (rec.getDetectedIssues() != null) {
            if (rec.getDetectedIssues().containsKey("CPU Throttling")) {
                content.append("- ✅ **Eliminate CPU throttling** - Faster response times\n");
            }
            if (rec.getDetectedIssues().containsKey("Memory Leak")) {
                content.append("- ✅ **Prevent OOMKilled crashes** - Improved stability\n");
            }
            if (rec.getDetectedIssues().containsKey("Connection Pool Exhaustion")) {
                content.append("- ✅ **Eliminate connection timeouts** - Better database performance\n");
            }
        }
        content.append("- ✅ **Optimized resource allocation** - Right-sized for workload\n");
        content.append("- ✅ **Improved reliability** - Fewer crashes and errors\n\n");

        // How to apply
        content.append("## 📝 How to Apply\n\n");
        content.append("### 1. Review Changes\n\n");
        content.append("Review the generated files in this PR:\n");
        content.append("- `k8s/deployment.yaml` - Kubernetes deployment with optimized resources\n");
        content.append("- `src/main/resources/application.properties` - Spring Boot configuration\n");
        content.append("- `helm/values.yaml` - Helm chart values\n\n");

        content.append("### 2. Test\n\n");
        content.append("```bash\n");
        content.append("# Deploy to staging environment\n");
        content.append("kubectl apply -f k8s/deployment.yaml\n\n");
        content.append("# Run load tests\n");
        content.append("# Monitor metrics\n");
        content.append("```\n\n");

        content.append("### 3. Merge & Deploy\n\n");
        content.append("After validation, merge this PR to apply optimizations to production.\n\n");

        content.append("---\n\n");
        content.append("**Generated by [SaveYourMoney](https://github.com/saveyourmoney) - AI-Powered Resource Optimization** 🚀\n");

        return GeneratedArtifacts.GeneratedFile.builder()
                .fileName("README.md")
                .filePath("README.md")
                .content(content.toString())
                .fileType(GeneratedArtifacts.FileType.README)
                .build();
    }

    /**
     * Generate Azure Pipelines YAML
     */
    private GeneratedArtifacts.GeneratedFile generateAzurePipeline(ResourceRecommendation rec) {
        String content = String.format("""
# Azure DevOps Pipeline - %s
# SaveYourMoney AI-Optimized Configuration

trigger:
  branches:
    include:
    - saveyourmoney/develop
    - saveyourmoney/feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  serviceName: %s
  imageTag: $(Build.BuildId)

stages:
- stage: Build
  displayName: 'Build Application'
  jobs:
  - job: Build
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        options: '-DskipTests'

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: build
        repository: $(serviceName)
        tags: $(imageTag)

- stage: Deploy
  displayName: 'Deploy to Kubernetes'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: 'Deploy to Kubernetes'
            inputs:
              action: deploy
              manifests: |
                k8s/deployment.yaml
""",
                rec.getServiceName(),
                rec.getServiceName()
        );

        return GeneratedArtifacts.GeneratedFile.builder()
                .fileName("azure-pipelines.yml")
                .filePath("azure-pipelines.yml")
                .content(content)
                .fileType(GeneratedArtifacts.FileType.AZURE_PIPELINE)
                .build();
    }
}
